// frontend/src/App.vue
<!--
SPDX-FileCopyrightText: 2026 AlitaBernachot

SPDX-License-Identifier: MIT
-->

<template>
  <div class="dark h-full flex flex-col bg-[#0d0d0f] text-white font-sans antialiased">
    <ChatView />
  </div>
</template>

<script setup lang="ts">
import ChatView from '@/components/ChatView.vue'
</script>

// frontend-client/src/App.tsx
// SPDX-FileCopyrightText: 2026 AlitaBernachot
//
// SPDX-License-Identifier: MIT

import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { Navbar } from './components/layout/Navbar'
import { Sidebar } from './components/layout/Sidebar'
import { ChatPage } from './pages/ChatPage'
import { FaqPage } from './pages/FaqPage'

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-[#0d0d0f] text-white font-sans antialiased flex flex-col">
        <Navbar />
        <div className="flex flex-1 overflow-hidden">
          <Sidebar />
          <main className="flex-1 flex flex-col overflow-hidden">
            <Routes>
              <Route path="/" element={<ChatPage />} />
              <Route path="/faq" element={<FaqPage />} />
              <Route path="*" element={<Navigate to="/" replace />} />
            </Routes>
          </main>
        </div>
      </div>
    </BrowserRouter>
  )
}
