// frontend/src/components/DataVizViewer.vue
<!--
SPDX-FileCopyrightText: 2026 AlitaBernachot

SPDX-License-Identifier: MIT
-->

<template>
  <div class="dataviz-wrapper flex flex-col gap-3">
    <!-- KPI cards -->
    <KpiCards v-if="dataviz.kpis?.length" :kpis="dataviz.kpis" />

    <!-- Charts (one per chart object) -->
    <ChartViewer
      v-for="(chart, i) in dataviz.charts"
      :key="i"
      :chart="chart"
    />

    <!-- Tables (one per table object) -->
    <TableViewer
      v-for="(table, j) in dataviz.tables"
      :key="j"
      :table="table"
    />
  </div>
</template>

<script setup lang="ts">
import type { DataVizPayload } from '@/types'
import ChartViewer from './DataViz/ChartViewer.vue'
import KpiCards from './DataViz/KpiCards.vue'
import TableViewer from './DataViz/TableViewer.vue'

defineProps<{ dataviz: DataVizPayload }>()
</script>

// frontend-client/src/components/DataViz/DataVizViewer.tsx
// SPDX-FileCopyrightText: 2026 AlitaBernachot
//
// SPDX-License-Identifier: MIT

import type { DataVizPayload } from '../../types'
import { KpiCards } from './KpiCards'
import { ChartViewer } from './ChartViewer'
import { TableViewer } from './TableViewer'

interface Props {
  dataviz: DataVizPayload
}

export function DataVizViewer({ dataviz }: Props) {
  return (
    <div className="flex flex-col gap-3">
      {dataviz.kpis && dataviz.kpis.length > 0 && <KpiCards kpis={dataviz.kpis} />}
      {dataviz.charts?.map((chart, i) => <ChartViewer key={i} chart={chart} />)}
      {dataviz.tables?.map((table, i) => <TableViewer key={i} table={table} />)}
    </div>
  )
}
